1. What does one need to do to use a module?
    * <font color=green>Anytime you use a module, you must IMPORT it into your program.</font>
1. Name a Module (not the DateTime Nodule) we looked at and write a line or 2 of code as an example using this module.
    * <font color=green>math.ceil()	#Rounds a number up to the nearest integer.</font>
    * <font color=green>math.fabs()	# Returns the absolute value of a number.</font>
1. What is a benefit of using Exception handling?
    * <font color=green>With this code device we can keep going past many errors.</font>
1. NumPy arrays are like what Python data type?
    * <font color=green>NumPy arrays are like lists in Python, arrays are an ordered sequence of elements. Both are also mutable and not fixed in size, which means iItems can be added and removed, making them very flexible to work with.</font>
1. What is one of the main benefits of using NumPy arrays.
    * <font color=green>Arrays are most useful when we must manipulate values of only one specific data type.</font>
1. What is one of the main requirements about the 'dtype' of NumPy arrays?
    * <font color=green>The default data type of a NumPy Array is floating point (np.float64).</font>
1. Of the 10 uses of NumPy, name 2.
    * <font color=green>np.nonzero() = used to count the number of nonzero elements present in array NumPy Count Nonzero Values in Python arrays
np.view() = create new array object that looks at the same data as the original array.</font>
1. Name one of the other libraries we'll use with NumPy?
    * <font color=green>Matplotlib and Pandas.</font>
1. What is the shape of NumPy arrays?
    * <font color=green>The shape of an array can be defined as the number of elements in each dimension.</font>
1. What is a Tensor?
    * <font color=green>Tensor is an array with 3+ dimensions.</font>
1. Name a reason why it's better using  NumPy for Data Analysis than using a Python List?
    * <font color=green>NumPy arrays are faster and more compact than Python lists.</font>
1. When creating an "empty" array, where do the elements come from?
    * <font color=green>The function empty creates an array whose initial content is random and depends on the state of the memory.</font>

In [1]:
#   1. Use the DateTime module to get Current Date and Time, and save it to a variable. Then extract just the Full month name form that variable.
import datetime as dt
# Get Current Date and Time
a = dt.datetime.now()
print("Current Date and Time ...", a)
print("Month ...", a.strftime("%B"))


Current Date and Time ... 2023-02-13 17:18:01.912154
Month ... February


In [39]:
#   2. Write a simple function that takes 2 parameters -- a  first name and a day name.
#    - Set a default value for the day name of Sunday.
def my_message(firstName, dayName):
    print("Hi", firstName +"! Happy"+ dayName +"!")     # - Have the function print out a greeting -- using the parameters -- that says something like "Hi first-name! Happy day-name!". Remember to use the variables in the greeting to replace first-name and day-name.  
my_message("Kenny", " Sunday")  # - Invoke this function with 2 variables.
my_message("Kenny", "") # - Invoke this function with 1 variable only.

#   3. Import NumPy, use one of the NumPy methods and create an array with a shape of ... (2, 3, 2). You can use the  method -- `.reshape()`
import numpy as np
a232 = np.arange(12).reshape((2, 3, 2))
print("The (2, 3, 2) array ...\n", a232)
#(0.1)(0.1)(0.1) how?
#(0.1)(0.1)(0.1)

#   4. Use NumPy `.linspace()` to create an array with 6 linearly spaced values between 0 and 20

ls = np.linspace(0, 20, num = 6)
print(ls)

#   5. Make a Deep Copy of the above array you created.
import copy
cy = copy.deepcopy(ls)
print(cy)

Hi Kenny! Happy Sunday!
Hi Kenny! Happy!
The (2, 3, 2) array ...
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[ 0.  4.  8. 12. 16. 20.]
[ 0.  4.  8. 12. 16. 20.]


6. What are 2 reasons we use NumPy arrays over Python Lists
* NumPy arrays occupy less memory and are fast compared to lists