Create a file and name it 5-Homework (this should be a Jupyter Notebook file so you can write MarkDown and Python code)


1. What does Pandas stand for?
    * <font color=green>Pandas stands for "Python Data Analysis Library".</font>

1. What are the 2 collections used in Pandas?
    * <font color=green>Series (1-dimensional) and DataFrame (2-dimensional).</font>

1. N ame 4 things Pandas can do for us.
    * <font color=green>Data Cleansing, data normalization, data visualization, and data inspection.</font>

1. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?
    * <font color=green>inplace = True.</font>

1. What is a CSV
    * <font color=green>Comma separated values file.</font>

1. When cleaning data what values do we not like in our data?
    * <font color=green>NaN values.</font>



In [20]:
#Please Complete this Coding Exercise:-
#Concatenate these 3 arrays into a new array named 'newArray'...
#        ([[25, 16]])
#        ([[11, 2], [13, 4]])
#        ([[7, 81], [5, 6], [11, 12]])
import numpy as np
a1 = np.array([[25, 16]])
a2 = np.array([[11, 2], [13, 4]])
a3 = np.array([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((a1, a2, a3), axis=0)
print("\nnewArray ...\n", newArray)

#Sort 'newArray' in order into 'sortedArray'
sortedArray = np.sort(newArray)
print("\nsortedArray...\n", sortedArray)
#Reshape the 'sortedArray' array, into a new array called 'reshapedArray', so it has 2 dimensions with a size of 2, 3.
reshapedArray = sortedArray.reshape(2, 2, 3)
print("\nreshapedArray...\n", reshapedArray)

#Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.
reshapedArray2 = reshapedArray.reshape(4, 3)
print("\nreshapedArray2...\n", reshapedArray2)

a, b, c, d = reshapedArray2

print("a = ", a)
print("b = ", b)
print("c = ", c)
print("d = ", d)



newArray ...
 [[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]

sortedArray...
 [[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]

reshapedArray...
 [[[16 25  2]
  [11  4 13]]

 [[ 7 81  5]
  [ 6 11 12]]]

reshapedArray2...
 [[16 25  2]
 [11  4 13]
 [ 7 81  5]
 [ 6 11 12]]
a =  [16 25  2]
b =  [11  4 13]
c =  [ 7 81  5]
d =  [ 6 11 12]


In [82]:
#Combined and sort the following arrays into one called 'comboArray' ...
import numpy as np
one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])
comboArray = np.sort(np.concatenate((one, two, three)))
print("\ncomboArray...\n", comboArray)

#Take 'comboArray' and perform the following slicing activities:
#print sec1 - the 2nd element
sec1 = comboArray[1]
print("\nThe 2nd element ...", sec1)

#print sec2 - all elements from the 3rd element to the last
sec2 = comboArray[2:]
print("\nall elements from the 3rd element to the last...\n", sec2)

#print sec3 - all elements from the 4th to the 14th elements
sec3 = comboArray[3:13]
print("\nall elements from the 4th to the 14th elements ...\n", sec3)

#print sec4 - the last 6 elements
sec4 = comboArray[-6:]
print("\nThe last 6 elements ...", sec4)

#print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
sec5 = comboArray[:-10]
print("\nall element from #0 up to and including #15, using the negative number method...\n", sec5)

#print sec6 - from #20 every even element to the end
sec6 = comboArray[16::2]
print("\nfrom #20 every even element to the end...\n", sec6)

#print sec7 - from the last element moving forward, every 5th element.
sec7 = comboArray[-1:0:-5]
print("\nfrom the last element moving forward, every 5th element...\n", sec7)



comboArray...
 [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]

The 2nd element ... 1

all elements from the 3rd element to the last...
 [ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]

all elements from the 4th to the 14th elements ...
 [ 3  4  5  6  7 10 11 12 13 14]

The last 6 elements ... [22 23 24 25 26 27]

all element from #0 up to and including #15, using the negative number method...
 [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]

from #20 every even element to the end...
 [20 22 24 26]

from the last element moving forward, every 5th element...
 [27 22 15 10  3]


In [95]:

#Using simple math operations, broadcast the addition (+), division (/), and multiplication (*) operations for these 2 arrays --
from numpy import array
import numpy as np
aa = array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
        [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
        [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])

bb = array([[17.0, 70.0, 10.7]])

#print("aa...",aa,"\nbb..",bb)

print("\nAddition ...\n", aa + bb)
print("\nDivision ...\n", aa / bb)
print("\nMultiplication ...\n", aa * bb)

#Use the NumPy Arithmetic functions to do the subtraction of the above two arrays in pont #7.

sub = np.subtract(aa, bb)
print("\nSubtraction ...\n", sub)







Addition ...
 [[[ 17.    70.    10.8 ]
  [ 27.    80.3   20.71]]

 [[ 37.    90.02  30.8 ]
  [ 47.   101.    41.  ]]

 [[ 57.4   94.    50.7 ]
  [ 32.    85.5   36.2 ]]]

Division ...
 [[[0.         0.         0.00934579]
  [0.58823529 0.14714286 0.93551402]]

 [[1.17647059 0.286      1.87850467]
  [1.76470588 0.44285714 2.8317757 ]]

 [[2.37647059 0.34285714 3.73831776]
  [0.88235294 0.22142857 2.38317757]]]

Multiplication ...
 [[[0.00000e+00 0.00000e+00 1.07000e+00]
  [1.70000e+02 7.21000e+02 1.07107e+02]]

 [[3.40000e+02 1.40140e+03 2.15070e+02]
  [5.10000e+02 2.17000e+03 3.24210e+02]]

 [[6.86800e+02 1.68000e+03 4.28000e+02]
  [2.55000e+02 1.08500e+03 2.72850e+02]]]

Subtraction ...
 [[[-17.   -70.   -10.6 ]
  [ -7.   -59.7   -0.69]]

 [[  3.   -49.98   9.4 ]
  [ 13.   -39.    19.6 ]]

 [[ 23.4  -46.    29.3 ]
  [ -2.   -54.5   14.8 ]]]
[[[ 0.    0.    0.1 ]
  [10.   10.3  10.01]]

 [[20.   20.02 20.1 ]
  [30.   31.   30.3 ]]

 [[40.4  24.   40.  ]
  [15.   15.5  25.5 ]]]

Above 

In [96]:
#Using modulo find all elements that are divisible by 3 from the multi-dimensional array under point #7 above.
import numpy as np
aa = array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
        [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
        [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])
print(aa)

divisible_by3 = aa[aa % 3 == 0]
print("\nAbove elements divisible_by_3 ...\n", divisible_by3)


[[[ 0.    0.    0.1 ]
  [10.   10.3  10.01]]

 [[20.   20.02 20.1 ]
  [30.   31.   30.3 ]]

 [[40.4  24.   40.  ]
  [15.   15.5  25.5 ]]]

Above elements divisible_by_3 ...
 [ 0.  0. 30. 24. 15.]


In [129]:
#Using Series, create a DataFrame that looks like this:
#
#Ingredients	Quantity	Unit
#Flour	4	cups
#Milk	1	cup
#Eggs	2	large
#Spam	1	can
#Name: Dinner, dtype: object
import pandas as pd

# Create pandas Series
Quantity = pd.Series([4,1,2,1],name='Quantity')
Unit = pd.Series(["cups","cup", "large", "can"],name='unit')
Ingredients  = pd.Series(["Flour","Milk", "Eggs", "Spam"],name='Ingredients')

# Combine two Series
df = pd.concat([Ingredients, Quantity, Unit], axis=1)
print("Dinner object ...\n", df)





Dinner object ...
   Ingredients  Quantity   unit
0       Flour         4   cups
1        Milk         1    cup
2        Eggs         2  large
3        Spam         1    can


In [117]:
#Take this data and create a DataFrame named studentData
import pandas as pd
Report = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
    }
studentData = pd.DataFrame(Report)
print(studentData)

#Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]
studentData.insert(2, "deserts", ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"],True)
print("\nStudentData with deserts inserted as column 2 ...\n", studentData)

#Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"
studentData.sort_values(by = ["Name", "address"], inplace = True)
print("\nstudentData sorting by column Name and then address ...\n", studentData)




      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket

StudentData with deserts inserted as column 2 ...
       Name  Height       deserts Qualification  address  Age        Pets  \
0      Jai     5.1     ice cream           Msc    Delhi   21         Dog   
1  janusha     6.2  Cashew Fudge            MA     Doha   23       Bunny   
2   Gaurav     5.1       waffels           Msc  Chennai   24  Chinchilla   
3     Anuj     5.2  Carrot Halwa           Msc   Dakhar   21      Parrot   

            sport  
0           Darts  
1      Basketball  
2  PaddleBoarding  
3         Cricket  

studentData sorting by column Name and then address ...
       Name  Height       deserts Q

In [137]:
#Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:
#import pandas as pd 

df = pd.DataFrame({"Cows": [12, 20], "Goats": [22, 19]}, index=["Year 1", "Year 2"])
df
df.to_csv("cows_and_goats.csv")
 

#(A) Using Pandas, make your own .CSV file with data on vegetables and save it. 
vegi = pd.DataFrame({'green vegi': ["kale", "broccoli","spinach"], 'red vegi': ["radish", "beets","red cabbages"]}, index=["dinner1", "dinner2","dinner3"])
print(vegi)
vegi.to_csv("vegi.csv")

#(B) Using Pandas, make a change to your CSV file, and save a copy with a different name.
vegi2 = pd.DataFrame({'green vegi': ["kale", "broccoli","spinach","bok choy","collard greens","cabbage"], 
                      'red vegi': ["radish", "beets","tomato","red bell pepper","red onion","carrot"]}, 
                      index=["dinner1", "dinner2","dinner3","dinner4", "dinner5","dinner6"])
print(vegi2)
vegi2.to_csv("vegi2.csv")

        green vegi      red vegi
dinner1       kale        radish
dinner2   broccoli         beets
dinner3    spinach  red cabbages
             green vegi         red vegi
dinner1            kale           radish
dinner2        broccoli            beets
dinner3         spinach           tomato
dinner4        bok choy  red bell pepper
dinner5  collard greens        red onion
dinner6         cabbage           carrot
